const date = new Date();
const options = { year: 'numeric', month: 'long', day: 'numeric' };
items=[
  {
    id: 1,
    imageSrc:"images/1.jpg",
    ratings : 4.5,
    likes: 1.4,
    brand: "Gucci",
    itemName: "Red dress",
    price: 1000,
    discount:25,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 2,
    imageSrc:"images/2.jpg",
    ratings : 4.2,
    likes: 0,
    brand: "CUKOO",
    itemName: "Women Padded Halter Neck Swimming Dress",
    price: 5000,
    discount: 30,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 3,
    imageSrc:"images/3.jpg",
    ratings : 4.1,
    likes: 1.4,
    brand: "NUEVOSDAMAS",
    itemName: "Women Red & White Printed A-Line Knee-Length Skirts",
    price: 100,
    discount: 20,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 4, 
    imageSrc:"images/4.jpg",
    ratings : 4.5,
    likes: 1.4,
    brand: "ADIDAS",
    itemName: "Indian Cricket ODI Jersey",
    price: 1000,
    discount:25,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 5,
    imageSrc:"images/5.jpg",
    ratings : 0,
    likes: 0,
    brand: "Roadster",
    itemName: "Pure Cotton T-shirt",
    price: 1000,
    discount:25,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 6,
    imageSrc:"images/6.jpg",
    ratings : 4.5,
    likes: 1.4,
    brand: "Nike",
    itemName: "Men ReactX Running Shoes",
    price: 1000,
    discount:0,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 7,
    imageSrc:"images/7.jpg",
    ratings : 0,
    likes: 2,
    brand: "The Indian Garage Co",
    itemName: "Men Slim Fit Regular Shorts",
    price: 1000,
    discount:25,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
  {
    id: 8,
    imageSrc:"images/8.jpg",
    ratings : 3.9,
    likes: 0.8,
    brand: "Nivea",
    itemName: "Men Fresh Deodrant 150ml",
    price: 1000,
    discount:25,
    returnDays: 14,
    date: date.toLocaleDateString('en-US', options),
  },
];
